### ISSUE TITLE
Improve custom dataset tutorial

### ISSUE THREAD

**Issue by boborbt** [makgyver/fluke#10]
**Describe the bug**
The documentation does not specify that the inputs of DataContainer have to be torch tensors.

**Comment by makgyver** [comment]
Fixed with commits [8656438](https://github.com/makgyver/fluke/commit/8656438b8dbf814bc50786c5429fce95e7929cb1) and [6af5057](https://github.com/makgyver/fluke/commit/6af50575cb9f9ee0ab04bbb10a9fd199a51e426e).
